require("core.plugins.betty")
require("core.plugins.catppuccin")
require("core.plugins.lsp")
require("core.plugins.lualine")
require("core.plugins.luatab")
require("core.plugins.telescope")
require("core.plugins.treesitter")
